/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javadriver_JavaDriver */

#ifndef _Included_javadriver_JavaDriver
#define _Included_javadriver_JavaDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javadriver_JavaDriver
 * Method:    driver_open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javadriver_JavaDriver_driver_1open
  (JNIEnv *, jobject);

/*
 * Class:     javadriver_JavaDriver
 * Method:    driver_close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javadriver_JavaDriver_driver_1close
  (JNIEnv *, jobject, jint);

/*
 * Class:     javadriver_JavaDriver
 * Method:    driver_read
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javadriver_JavaDriver_driver_1read
  (JNIEnv *, jobject, jint);

/*
 * Class:     javadriver_JavaDriver
 * Method:    driver_write
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javadriver_JavaDriver_driver_1write
  (JNIEnv *, jobject, jint);

/*
 * Class:     javadriver_JavaDriver
 * Method:    driver_ioctl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_javadriver_JavaDriver_driver_1ioctl
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
